version: "2"
run:
  go: "1.24"
linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 5
    gocyclo:
      min-complexity: 70
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: table_input.go
      - linters:
          - staticcheck
        path: table_display.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
